### ISSUE TITLE
Intellij gives me 4 errors

### ISSUE THREAD

**Issue by CoolTomatos** [SERG-Delft/mooc-software-testing#3]
https://github.com/SERG-Delft/mooc-software-testing/blob/0b2ffa1c5b225b57eb809bcdefe3e930b5d908bb/pom.xml#L84-L86

Two of the errors say that 
> Element `systemPropertyVariables` is not allowed here

And the other two errors say that
> Cannot resolve symbol `'jacoco-agent.destfile'`

**Comment by binarywang** [comment]
why did you close it?

**Comment by massiri** [comment]
why did you close it? I have the same PB
